### ISSUE TITLE
谷歌插件翻译不全

### ISSUE THREAD

**Issue by ma3252788** [roojay520/bobplugin-google-translate#1]
复制了一段话，但是插件显示不全，每次都是同样的长度，其他的没问题。具体情况如下图：
![](https://ypyssl.machunjie.com/machunjie/20200915184644.png)

**Comment by roojay520** [comment]
@ma3252788  感谢反馈, 0.1.3 版本已经修复此问题 [0.1.3](https://github.com/roojay520/bobplugin-google-translate/releases/download/v0.1.3/google-translate-v0.1.3.bobplugin)
