### ISSUE TITLE
翻译插件失效

### ISSUE THREAD

**Issue by lrunze** [roojay520/bobplugin-google-translate#14]
版本号：0.4.2
Bob版本号：0.6.1 [4]
设置：缓存开启，接口国内google，接口版本是新版
问题描述：翻译无法使用，看起来是连不上google翻译

望解决，谢谢~

**Comment by Evan-Future** [comment]
> 版本号：0.4.2
> Bob版本号：0.6.1 [4]
> 设置：缓存开启，接口国内google，接口版本是新版
> 问题描述：翻译无法使用，看起来是连不上google翻译
> 
> 望解决，谢谢~

+1，感觉好像是接口出问题了，我换成了自己的私人密钥就很流畅了，怀疑是插件用的私人密钥超过免费50万字符数量导致的

**Comment by roojay520** [comment]
旧版本的国内接口失效了，新版本 RPC 接口目前正常使用，但是最近 Google 也加强了接口风险策略检测

**Comment by Evan-Future** [comment]
> 旧版本的国内接口失效了，新版本 RPC 接口目前正常使用，但是最近 Google 也加强了接口风险策略检测

没关系，我已经使用国际版接口了，而且也用的私钥，一切正常

**Comment by lrunze** [comment]
没信用卡的已经哭晕（可以close issue了

**Comment by jason2001-21** [comment]
出问题的人现在只能用国际版的或私人密钥，暂时起码还能用

**Comment by lrunze** [comment]
thanks for the update!
