### ISSUE TITLE
" ' "不能正确显示

### ISSUE THREAD

**Issue by ly5902534** [roojay520/bobplugin-google-translate#15]
<img width="160" alt="image" src="https://user-images.githubusercontent.com/61930853/183249106-7c56a345-1cda-4925-ab38-1b79d2358b44.png">
I won&#39;t have a ........ 
" ' "不能正确显示

**Comment by roojay520** [comment]
@ly5902534  
我这边测试能正常显示：
<img width="413" alt="image" src="https://user-images.githubusercontent.com/11495164/183376082-21df289b-6dbe-4690-9659-cc44f4fa9268.png">

看你发的这个截图使用应该是不是本插件，看着像是这个插件：https://github.com/tingv/bobplugin-google-translate

**Comment by ly5902534** [comment]
&#39; 在GitHub显示为 ' ，其实我粘贴的是 Can空格&#39;t      我不知道这是什么编码格式，其他的插件没问题

**Comment by roojay520** [comment]
@ly5902534 `&#` 这种格式开头的一般是 [HTML 实体字符]( https://developer.mozilla.org/zh-CN/docs/Glossary/Entity) `&#39;`解码对应的就是`'` 你使用的这个插件应该是在解析翻译结果时编码出错了

你补充的截图不是本仓库对应的插件，本仓库的插件截图：
<img width="713" alt="image" src="https://user-images.githubusercontent.com/11495164/186047056-4665e1e9-0024-45d0-809c-e7cf3b5fc80f.png">

本仓库插件对应的下载地址是：[google-translate-v0.5.0.bobplugin](https://github.com/roojay520/bobplugin-google-translate/releases/download/v0.5.0/google-translate-v0.5.0.bobplugin)

**Comment by ly5902534** [comment]
现在没问题了，我之前应该是安装过，应该是保留了其中一个。对比观察一下，应该没有差异吧？
