### ISSUE TITLE
请问 WEB/RPC/混合版 三种在具体是什么区别？

### ISSUE THREAD

**Issue by cyhhao** [roojay520/bobplugin-google-translate#16]
都是 Web 端的 API 嘛？

因为我同时用了bob自带的密钥版 google translate，发现有时跟web上的翻译不太一样，想多一个web版的翻译做参考。

想了解这三种具体实现原理，如果想要 web 版的翻译是不是应该只选 WEB？如果选混合版，什么情况下会自动切换？

**Comment by roojay520** [comment]
@cyhhao  
- WEB: 采用 Google 翻译老版本网页接口进行翻译，缺点是 Google 翻译之前有一次更新之后 `.cn` 域名下获取不到 `tkk` 导致只能使用`.com`，所以对网络环境有要求；
- RPC: 采用 Google 翻译新版本网页的 RPC 接口进行翻译，优点是是支持`.cn`域名，缺点是这个接口有一个加密参数没有办法获取到，会导致段落翻译的质量不行；
- 混合版：单词翻译采用 RPC 接口，段落翻译采用移动端的 WEB 接口；
