### ISSUE TITLE
 google翻译中国停了后，是否插件功能失效了？

### ISSUE THREAD

**Issue by zhangweibo413** [roojay520/bobplugin-google-translate#17]
提示“插件未返回有效结果”，是否翻译功能受google翻译中国区停用的影响？

**Comment by zhangweibo413** [comment]
不好意思，解决了，换过国际接口就好了

**Comment by yang531** [comment]
> 不好意思，解决了，换过国际接口就好了

请问是怎么换国际接口解决这个问题的

**Comment by yang531** [comment]
> > 不好意思，解决了，换过国际接口就好了
> 
> 请问是怎么换国际接口解决这个问题的

哈哈哈哈哈，不好意思，我看见国际接口了，知道怎么切换了

**Comment by JimmyLX** [comment]
> 

怎么切换呀, 是要重新安装吗

**Comment by yang531** [comment]
> > 
> 
> 怎么切换呀, 是要重新安装吗

偏好设置-》翻译服务-》Google翻译-》接口域名选择 google.com(国际)

不过可能需要vpn才能继续用

**Comment by JimmyLX** [comment]
谢谢回复! 一直在插件设置里找, 原来是在翻译服务里面
