### ISSUE TITLE
英译中时，采用小写会有更多释义

### ISSUE THREAD

**Issue by Tuzkiss** [roojay520/bobplugin-google-translate#2]
基于 v0.2.2 版本
--- 

以 good 单词为例：

默认貌似请求参数时为 q=Good，释义如下：
![image](https://user-images.githubusercontent.com/5539512/95571346-d9a90800-0a5a-11eb-9efc-35dccde97f4f.png)

将待翻译的 Text 转化为小写时，可以获得更多释义:
```
text = text.toLowerCase();
```

![image](https://user-images.githubusercontent.com/5539512/95571284-c26a1a80-0a5a-11eb-8892-4d06eefcdfe1.png)

**Comment by roojay520** [comment]
@Tuzkiss  感谢反馈，已在0.3.1版本中优化: [google-translate-v0.3.1.bobplugin](https://github.com/roojay520/bobplugin-google-translate/releases/download/v0.3.1/google-translate-v0.3.1.bobplugin)
