### ISSUE TITLE
插件在apple book软件中使用，不会对选中内容进行翻译

### ISSUE THREAD

**Issue by lge6** [roojay520/bobplugin-google-translate#20]
用快捷键对apple book中的内容进行选中翻译，插件会直接不翻译，可能是因为加了引号的原因？

**Comment by roojay520** [comment]
@lge6 
是整个 bob 软件直接不翻译还是单独这个插件不工作？

在我测试的情况下，在 `Apple Book` 里面选择单个单词或者少量单词都是可以正常翻译的，如果选择一个段落的话 Bob 直接提示不支持当前软件划词翻译。

**Comment by lge6** [comment]
选择的内容是一句话到一段话的长度。其他两个插件openai和openL可以翻译，但是google会直接显示原文（不过也没提示 不支持当前软件划词翻译）

**Comment by roojay520** [comment]
我这边测试暂时复现不了你的这种情况，方便提供下示例吗？
选择少量单词：
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/11495164/226496224-5a020bce-f74f-437f-a2ed-d5859eef6d58.png">
选择句子：
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/11495164/226496521-efbcdd2d-4702-490c-a200-353f4434ddcd.png">

**Comment by lge6** [comment]
我今天又试了下，选择较长内容，google翻译又正常了，如果下次再出现，我会截图，谢谢

**Comment by lge6** [comment]
<img width="393" alt="1" src="https://user-images.githubusercontent.com/26705002/226561794-915eaf81-7f4a-484e-bc1a-281a5ce89319.png">
大概是这样，选取一句话会出现这样的情况，应该是和引用有关

**Comment by roojay520** [comment]
好的，下次遇到问题再反馈，那我先关掉这个 issues 了
