### ISSUE TITLE
英文缩写中自动添加空格?

### ISSUE THREAD

**Issue by Wbn-369** [roojay520/bobplugin-google-translate#21]
![1641680233609_ pic](https://user-images.githubusercontent.com/82264069/229016200-3c5c822e-6e16-4b04-b3dd-5d3b1e14190a.jpg)
Google 官网没有这个问题，麻烦解决一下哈

**Comment by roojay520** [comment]
这个地方应该是拆分蛇形变量命名之类的导致的问题，有空了新增个配置项选择是否开启

**Comment by Wbn-369** [comment]
辛苦辛苦🌹

**Comment by roojay** [comment]
@Wbn-369 新版本 [google-translate-v0.7.1](https://github.com/roojay520/bobplugin-google-translate/releases/tag/v0.7.1) 已经添加了字符串拆分可配置项，关闭这个就行：

<img width="459" alt="image" src="https://user-images.githubusercontent.com/11495164/230761161-49adcae6-c11e-4f09-865e-dbd05a9e9886.png">
