### ISSUE TITLE
秘钥获取失败

### ISSUE THREAD

**Issue by ztwqy6688o** [roojay520/bobplugin-google-translate#3]
翻译时显示秘钥获取失败

**Comment by roojay520** [comment]
之前也有反馈，经过排查应该是 google.cn 接口做了限制。
临时解决方案：先使用一次 google.com 翻译，获取到 token 值之后再切回 google.cn 使用

https://github.com/ripperhe/Bob/issues/106#issue-734270282

**Comment by ztwqy6688o** [comment]
好的，已可用

**Comment by goomadao** [comment]
刚出现了这个问题，不过我一直用的都是google.com。切换到google.cn正常使用了
