### ISSUE TITLE
请问为什么不能中译英

### ISSUE THREAD

**Issue by Uncle-Gao** [roojay520/bobplugin-google-translate#4]
如图，谷歌插件不能将中文翻译为英文，插件版本是0.33，Bob版本是0.52

![image](https://user-images.githubusercontent.com/49703110/98470357-0863fb00-2220-11eb-928a-4ba203896de1.png)

**Comment by Uncle-Gao** [comment]
已解决，是这一个中文词语不能被翻译，不知道为什么，其他词语没什么问题。
![image](https://user-images.githubusercontent.com/49703110/98470732-b1abf080-2222-11eb-8050-007052dd1e90.png)

**Comment by roojay520** [comment]
尝试自动检测或者指定语言均未复现这种情况
![image](https://user-images.githubusercontent.com/11495164/98522975-4f99cc80-22b0-11eb-8b05-78d8c17768ca.png)
![image](https://user-images.githubusercontent.com/11495164/98523147-8a9c0000-22b0-11eb-92b3-df110eb0fc32.png)

**Comment by roojay520** [comment]
低概率可能是接口抽风，后面遇到再分析
