### ISSUE TITLE
请问没有语音吗?

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [roojay520/bobplugin-google-translate#5]
请问没有谷歌语音吗?

**Comment by roojay520** [comment]
目前查单词有tts发音，句子还没有 
![image](https://user-images.githubusercontent.com/11495164/99351255-29d97c80-28db-11eb-8b60-024f05c049cc.png)

**Comment by xiaolongGitHub1498** [comment]
> 目前查单词有tts发音，句子还没有
> ![image](https://user-images.githubusercontent.com/11495164/99351255-29d97c80-28db-11eb-8b60-024f05c049cc.png)

您好 发现了一个问题 翻译会吧name单词翻译为那么...

**Comment by roojay520** [comment]
@xiaolongGitHub1498 这个问题是 Google 翻译的问题，暂时没法解决 ![Screenshot_20201118-213144](https://user-images.githubusercontent.com/11495164/99536570-84f79600-29e5-11eb-8875-fb8b44897d6d.jpg)

**Comment by xiaolongGitHub1498** [comment]
@roojay520 您好 插件是默认为自动检测语言的吧? bob的语言转换设置是不是不会起作用
![image](https://user-images.githubusercontent.com/26108004/99549888-14f10c00-29f5-11eb-8a21-158924d18f42.png)

**Comment by xiaolongGitHub1498** [comment]
@roojay520 我试了下谷歌翻译确实在自动检测下是会把name翻译为那么 但是如果指定语言的话就不会出这个问题
![image](https://user-images.githubusercontent.com/26108004/99551308-a44aef00-29f6-11eb-9dab-ed05d6f6a849.png)

但是在bob里还是会出现这个问题 不知是不是谷歌翻译api的问题
![image](https://user-images.githubusercontent.com/26108004/99551438-d1979d00-29f6-11eb-8269-289e4cbb346d.png)

**Comment by roojay520** [comment]
bob里面出现这种指定语言后还是这个翻译结果是因为缓存的缘故，这周末如果有时间的话我修复一下

**Comment by xiaolongGitHub1498** [comment]
@roojay520 好的 多谢 :v::v::v:

**Comment by roojay520** [comment]
@xiaolongGitHub1498  修复了缓存导致语言切换之后翻译结果不变的情况，后面有时间了考虑把语音部分抽离出来单独做个TTS插件  [v0.3.5](https://github.com/roojay520/bobplugin-google-translate/releases/tag/v0.3.5)
