### ISSUE TITLE
再次出现秘钥获取失败

### ISSUE THREAD

**Issue by ztwqy6688o** [roojay520/bobplugin-google-translate#6]
此次秘钥获取失败，切换成.com翻译也同样显示

**Comment by ma3252788** [comment]
遇到同样问题。。不知道是不是bob升级了的缘故？

**Comment by roojay520** [comment]
@ma3252788 @ztwqy6688o Google Translate 在这个月更新了翻译接口调用方式，早上分析了一下网页版本，接口似乎从原来的 rest 接口 /translate_a/single 改为 rpc 多段调用 /_/TranslateWebserverUi/data/batchexecute，这两天我研究一下看看如何模拟调用 
![image](https://user-images.githubusercontent.com/11495164/100689578-b138ec80-33bf-11eb-8198-09650f068590.png)

**Comment by ma3252788** [comment]
> @ma3252788 @ztwqy6688o Google Translate 在这个月更新了翻译接口调用方式，早上分析了一下网页版本，接口似乎从原来的 rest 接口 /translate_a/single 改为 rpc 多段调用 /_/TranslateWebserverUi/data/batchexecute，这两天我研究一下看看如何模拟调用
> ![image](https://user-images.githubusercontent.com/11495164/100689578-b138ec80-33bf-11eb-8198-09650f068590.png)

原来是这样，我还以为是bob版本的问题。期待大神早日修复~~

**Comment by roojay520** [comment]
晚上研究了一下 Google 翻译新版本的接口，目前已经能在 nodejs 端跑通，但 bob 使用的是 JSCore，同样的解析代码在 bob 中无法执行再加上 bob 调试不太方便，还需要一定时间去调试适配

**Comment by char1eslu** [comment]
非常感谢，辛苦

**Comment by roojay520** [comment]
@char1eslu @ma3252788 @ztwqy6688o 更新了一个临时版本可以先用着，新版本正在适配中  https://github.com/roojay520/bobplugin-google-translate/releases/download/v0.3.5/google-translate-v0.3.5.bobplugin

**Comment by char1eslu** [comment]
可以了，非常感谢
________________________________
发件人: Roojay <notifications@github.com>
发送时间: 2020年12月2日 10:32
收件人: roojay520/bobplugin-google-translate <bobplugin-google-translate@noreply.github.com>
抄送: Charles Lu <charles_lu@live.cn>; Mention <mention@noreply.github.com>
主题: Re: [roojay520/bobplugin-google-translate] 再次出现秘钥获取失败 (#6)


@char1eslu<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchar1eslu&data=04%7C01%7C%7Ce15c7393b9674df120fe08d8966a7468%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637424731241103271%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nhBJ9k3JMqk%2FG0I09pcbbPYmtHdqoJxU3EhS4ezxcc4%3D&reserved=0> @ma3252788<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fma3252788&data=04%7C01%7C%7Ce15c7393b9674df120fe08d8966a7468%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637424731241113268%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UrHgGzpaYiz6IPZMDn7FhfmzqtnlQv4b08ZVhfhWOA8%3D&reserved=0> @ztwqy6688o<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fztwqy6688o&data=04%7C01%7C%7Ce15c7393b9674df120fe08d8966a7468%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637424731241123261%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nXl6rLLQddPpmmoh9J87sqK%2BUlTZvpao5%2BWz9jLFkbE%3D&reserved=0> 更新了一个临时版本可以先用着，新版本正在适配中 https://github.com/roojay520/bobplugin-google-translate/releases/download/v0.3.5/google-translate-v0.3.5.bobplugin<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Froojay520%2Fbobplugin-google-translate%2Freleases%2Fdownload%2Fv0.3.5%2Fgoogle-translate-v0.3.5.bobplugin&data=04%7C01%7C%7Ce15c7393b9674df120fe08d8966a7468%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637424731241133256%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KWbem1xa0AZohep8%2BXJsmpHokCALZ2yctKb%2F1AxMxQQ%3D&reserved=0>

―

**Comment by winsonet** [comment]
非常感謝！！
