### ISSUE TITLE
秘钥获取失败😭

### ISSUE THREAD

**Issue by guomaimang** [roojay520/bobplugin-google-translate#7]
又出现获取秘钥失败了，不只是这一个谷歌翻译的bob插件，几乎其他的谷歌翻译bob插件都出现这种情况了。😭今天怎么上课😭

**Comment by roojay520** [comment]
#6  暂时先用百度或者有道的吧，google 更新了接口需要适配

**Comment by winsonet** [comment]
支持支持，希望能儘快修復，謝謝啦！！

**Comment by roojay520** [comment]
后面更新情况在 #6 统一说明
