### ISSUE TITLE
服务异常: 请求频率过快, 请稍后再试

### ISSUE THREAD

**Issue by char1eslu** [roojay520/bobplugin-google-translate#8]
Bob：0.5.3，插件：0.3.5
<img width="400" alt="image" src="https://user-images.githubusercontent.com/20885743/102858319-074ffb80-4465-11eb-9f94-e7aa30244c5f.png">

**Comment by char1eslu** [comment]
已恢复

**Comment by char1eslu** [comment]
最近经常出现 接口请求频率过快唉

**Comment by roojay520** [comment]
> 最近经常出现 接口请求频率过快唉

这个可能是 Google 的接口最近做了调整，限制了请求频率

**Comment by char1eslu** [comment]
> > 最近经常出现 接口请求频率过快唉
> 
> 这个可能是 Google 的接口最近做了调整，限制了请求频率

好的，了解了，谢谢解答
