### ISSUE TITLE
一上午一直提示 请求频率过快, 请稍后再试

### ISSUE THREAD

**Issue by guomaimang** [roojay520/bobplugin-google-translate#9]
![image](https://user-images.githubusercontent.com/47519540/106985575-b0984a00-67a4-11eb-9b86-eb05c0460a16.png)

**Comment by roojay520** [comment]
这个我也遇到了，Google 最近更新了接口估计得对老版本接口做了请求频率限制，暂时没有办法解决。新版本的 Google API 解析目前只在 nodejs 环境下跑通过，暂时没法在 Bob 下跑通，最近没太多时间去研究，等过段时间不忙了我看能否寻找到其它绕过方法

**Comment by liushawulan** [comment]
今天又出现了这个问题。不知道是接口更新，还是用户太多了。烦请老哥有空时看下。

**Comment by roojay520** [comment]
@liushawulan @guomaimang  [v0.4](https://github.com/roojay520/bobplugin-google-translate/releases/download/v0.4.1/google-translate-v0.4.1.bobplugin) 版本已经发布, 适配了 Google 翻译新版的 RPC 接口，可以更新尝试下， 有问题随时反馈

**Comment by liushawulan** [comment]
> @liushawulan @guomaimang [v0.4](https://github.com/roojay520/bobplugin-google-translate/releases/download/v0.4.1/google-translate-v0.4.1.bobplugin) 版本已经发布, 适配了 Google 翻译新版的 RPC 接口，可以更新尝试下， 有问题随时反馈

好的，谢谢。：）
